// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Todos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("05dfb8a1-b918-4420-b70c-b68806bd6ebd"),
                            Content = "This is the first todo",
                            CreateTime = new DateTime(2024, 3, 17, 22, 50, 22, 32, DateTimeKind.Utc).AddTicks(1038),
                            Status = 1,
                            Title = "First Todo",
                            UpdatedDate = new DateTime(2024, 3, 17, 22, 50, 22, 32, DateTimeKind.Utc).AddTicks(1039)
                        },
                        new
                        {
                            Id = new Guid("a3852b7e-1e9d-4e48-83dd-fd44af63629a"),
                            Content = "This is the second todo",
                            CreateTime = new DateTime(2024, 3, 17, 22, 50, 22, 32, DateTimeKind.Utc).AddTicks(1041),
                            Status = 0,
                            Title = "Second Todo",
                            UpdatedDate = new DateTime(2024, 3, 17, 22, 50, 22, 32, DateTimeKind.Utc).AddTicks(1041)
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ac6ae43-86ec-40f4-a3cf-45e26d341ac1"),
                            CreateTime = new DateTime(2024, 3, 17, 22, 50, 22, 32, DateTimeKind.Utc).AddTicks(1154),
                            Email = "user@example.com",
                            FirstName = "Can",
                            LastName = "Doe",
                            Password = "D0B3749570B6AA9155E3CAF5E42D9AEFE826600AF86A80EE4051CE6F76FA5D0D:2A59480760E144B6C0BC4954D3C2B37B:50000:SHA256",
                            UpdatedDate = new DateTime(2024, 3, 17, 22, 50, 22, 32, DateTimeKind.Utc).AddTicks(1154)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
